### ISSUE TITLE
Load config only once per run

### ISSUE THREAD

**Issue by achilles42** [gojektech/proctor#17]
- Move InitConfig to main.go
- Don't make config as Singleton
- Clean-up the existing test for configs

**Comment by olttwa** [comment]
Issue resolved by pull request #50

**Comment by olttwa** [comment]
Issue resolved by pull request [#50](https://github.com/gojektech/proctor/pull/50)

**Comment by olttwa** [comment]
Issue resolved by pull request [#50](https://github.com/gojektech/proctor/pull/50)
