### ISSUE TITLE
Remove proc command from proctor CLI

### ISSUE THREAD

**Issue by jensoncs** [gojektech/proctor#22]
As a user,
I don't want to type the redundant word `proc` everytime I `list/describe/execute` procs.

**Comment by olttwa** [comment]
This issue makes sense because currently proctor doesn't have any other functionality than `procs`. We'll support both ways of using procs for now. We'll deprecate the `proc` command in a major release. And introduce it back in future when namespacing is needed for multiple features of proctor.
