### ISSUE TITLE
Notification on Proc completion

### ISSUE THREAD

**Issue by olttwa** [gojektech/proctor#5]
As a user,
I want to be notified when the proc I executed completes.

So that I don't have to pay attention to the progress of procs in execution, and can focus on something else.

Once a proc reaches completion, proctor should notify me about that, and let me know if the proc completed successfully or failed.

Out of scope:
Multiple channels of notification.
For now, proctor will only accept an api during executing a proc. It will notify on that api once the proc reaches completion.
Implement multiple channels for notification later.

**Comment by jensoncs** [comment]
Added callback functionality. User Needs to pass callback_url to get job status.
